export const responses = [
  'Never will you ever ever, ever ever',
  'I don\'t think so, Tim',
  'Wonder what I should have for lunch...',
  'I almost feel bad for you. Almost',
  'Noone would agree to saying maybe',
  'If the shoe fits, then..no',
  'Yes, but no.',
  'Come back with a better question',
  'I have a question for YOU: How dare you?',
  'I require better questions. NEXT!', 
  'Is water wet?',
  '🤏',
  '🙏',
  '😓',
  '💩',
  '🤣',
  '🤐',
  '🌧',
  'Uh huh, uh huh',
  'Imagine the most optimistic person in the world. Now imagine them telling you no',
  'Y to the E to the S',
  'N to the O',
  'Mykenzie has the answer to that'
];
